export const SAVE_WORKPLACE_START = "SAVE_WORKPLACE_START";
export const SAVE_WORKPLACE_SUCCESS = "SAVE_WORKPLACE_SUCCESS";
export const SAVE_WORKPLACE_FAILER = "SAVE_WORKPLACE_FAILER";

export const FETCH_WORKPLACE_START = "FETCH_WORKPLACE_START";
export const FETCH_WORKPLACE_SUCCESS = "FETCH_WORKPLACE_SUCCESS";
export const FETCH_WORKPLACE_FAILER = "FETCH_WORKPLACE_FAILER";

export const SHOW_ADD_EDIT = "SHOW_ADD_EDIT";
export const CLOSE_ADD_EDIT = "CLOSE_ADD_EDIT";

export const DELETE_WORKPLACE_SUCCESS = "DELETE_WORKPLACE_SUCCESS";
export const DELETE_WORKPLACE_FAILER = "DELETE_WORKPLACE_FAILER";

export const CLEAR_STORE = "CLEAR_STORE";
