export const ADD_EMPLOYEE_START = "ADD_EMPLOYEE_START";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILER = "ADD_EMPLOYEE_FAILER";

export const FETCH_EMPLOYEE_START = "FETCH_EMPLOYEE_START";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILER = "FETCH_EMPLOYEE_FAILER";
